### ISSUE TITLE
Plugin error after upgrade

### ISSUE THREAD

**Issue by gstach** [Opencast-Moodle/moodle-repository_opencast#16] opened 2021-07-08 05:17 UTC
I did an manual update to the filter and repository plugin on our moodle Server. After that the repository plugin isn't working any more.
=> Fehler beim Lesen der Datenbank (error on reading the database) (see attached image)
I tried to remove the plugin an then to reinstall it, but the same error occured.

![oc_moodle_repository_error](https://user-images.githubusercontent.com/9291386/124866133-2dca2400-dfbc-11eb-9552-1605fa8c61d7.PNG)

I only get this error by selecting "Kurs-Videos" which is the Opencast repository. All other repositories are working.
What can i do to get the plugin working again? (I'm on Moodle 3.11)
Kind regards
Gerald

**Comment by moodle-mw** [comment] 2021-08-10 14:31
Unfortunately, I can confirm this issue also with Moodle 3.10, using filter_opencast (2018031902), tool_opencast (v3.11-r2, 2021062500) and repository_opencast (2021060400).
Greetings,
Michael

**Comment by TamaraGunkel** [comment] 2021-08-11 14:50
Hey,
I suggest using the commit bafb224d0508c3f073d24c876c5757f0a91f7e8a as repository version.
I did some development on the tool which will be released in September. Both master versions should work well together (although I cannot recommend using them in production since they are not release-ready).
However, I think the confusion arised because we don't have release versions for the repository as we're currently busy with the developments of the other plugins. Thus, I added an unofficial release that should work well with the current tool release.
At some point in the future, I'll add the repository to the Moodle Plugin directory so that we have the same release cycle like the other plugins.

**Closed** 2021-08-11 14:52 UTC

**Comment by moodle-mw** [comment] 2021-08-11 15:16
Hello @TamaraGunkel,

this was not the case. Your last [commit](https://github.com/Opencast-Moodle/moodle-repository_opencast/commit/5519b7aedff062e8e34640737f26ed6d0b6be846) was our problem. ;-)

So we reverted the code and now the repository function works as expected again. ;-)

Thanks & Greetings,
Michael

**Comment by gstach** [comment] 2021-08-11 15:41
i can confirm, that rollback of the last commit solves the problem. :-)
Greetings
Gerald
